services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"  
    environment:
      - MONGO_URL=mongodb://mongo:27017/database  
    depends_on:
      - mongo 

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  
    

