---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBwSk9lsugiBc6D7kgmOJsP9z89JR1RJvwLhgrbYy8biVFrtsMd2kLbzscZXZ7KGCFTCpegLxhPjJhUTCvRnRaCTdsrjacV8yf5cjQcuTh543s/F5zEaAFp5nMf0HwekAMLOqCafQ6t7AxrFhb9G9no4ITpygeActXQLKd5iux2yP95Hor8r0R/lVK4MpGet/HSkAlf7f2dYt42DFAmuRqoLRHG0EDgKbXnoyz9kzdZ2ZRecvBpU1DnJjwA4z/MwhRE0PGzkU4UbTB8iMyGTjbDmkMJUF7YU1g3q7ebLujSCmmXuvedqRPVx6pdzjLAdQzjyv2P8Im5Ub0tUDteIZePIbvHXepjFz02x+nLB2hXeu5Yt4eIn8svxe4R1gQQ4TIuNXqejxCjausPZbTiA+GOSK1stM/JXgmHkNIaKMuxow+JVoF3Jjj7WYYjevH8MEXREY4Rmy0qG+pHqxJEO1N/WWt2F5EyQvfCDS6gSGSQYXJT9UBly7SBjRxtBenTn3YyVTxOQdet0/NlFzIOPvnia1+/a7NGmFvORuT1huwubPjHzIkN0rKOXfU8x6K0qH6QqIWkMGikvNWzuFeXzCwEzGcZsk/DbMfkqw2QYk5W4po8+nLcu9FhcA4eohy6SvI4wZK3FsUiqAftyt6U8TVmwKgqVypUYMqgUlhVyitF0DWlvvEt4mrESHxccI7PmdrbC9M=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
